---

  - name: clone tlog
    git:
      repo: https://github.com/Scribery/tlog.git
      dest: /tmp/{{ source_dir }}

  - name: build tlog
    shell: |
      cd /tmp/tlog-source
      autoreconf -i -f
      ./configure && make dist
      rpmbuild -tb tlog-*.tar.gz

  - name: install tlog
    shell: yum install -y /root/rpmbuild/RPMS/{{ arch }}/tlog*

  - name: tlog cleanup
    file: name=/root/rpmbuild state=absent

  - name: tlog cleanup source
    file: name=/tmp/{{ source_dir }} state=absent

  - name: copying tlog-rec.conf
    template: src=tlog-rec.conf.j2 dest=/etc/tlog/tlog-rec.conf

  - name: copying tlog-play.conf
    template: src=tlog-play.conf.j2 dest=/etc/tlog/tlog-play.conf
